import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                surface: "#fcf9f8",
                "surface-dim": "#dcd9d9",
                "surface-bright": "#fcf9f8",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f6f3f2",
                "surface-container": "#f0eded",
                "surface-container-high": "#eae7e7",
                "surface-container-highest": "#e5e2e1",
                "on-surface": "#1c1b1b",
                "on-surface-variant": "#5a4139",
                "inverse-surface": "#313030",
                "inverse-on-surface": "#f3f0ef",
                outline: "#8e7067",
                "outline-variant": "#e2bfb4",
                "surface-tint": "#ad3300",
                primary: "#a93200",
                "on-primary": "#ffffff",
                "primary-container": "#d1430a",
                "on-primary-container": "#fffbff",
                "inverse-primary": "#ffb59e",
                secondary: "#bb0013",
                "on-secondary": "#ffffff",
                "secondary-container": "#e71520",
                "on-secondary-container": "#fffbff",
                tertiary: "#0a47ee",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#3e65ff",
                "on-tertiary-container": "#fffbff",
                error: "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                background: "#fcf9f8",
                "on-background": "#1c1b1b",
                "surface-variant": "#e5e2e1",
            },
            fontFamily: {
                sora: ["Sora", "sans-serif"],
                inter: ["Inter", "sans-serif"],
                mono: ["JetBrains Mono", "monospace"],
            },
            fontSize: {
                "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
                "headline-lg": ["48px", { lineHeight: "1.2" }],
                "headline-md": ["32px", { lineHeight: "1.3" }],
                "headline-sm": ["24px", { lineHeight: "1.4" }],
                "body-lg": ["18px", { lineHeight: "1.6" }],
                "body-md": ["16px", { lineHeight: "1.6" }],
                "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em" }],
            },
            maxWidth: {
                container: "1280px",
            },
            borderRadius: {
                sm: "0.125rem",
                DEFAULT: "0.25rem",
                md: "0.375rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
        },
    },
    plugins: [],
};

export default config;
